"""Generates a color-override snippet for Powerlevel10k
(https://github.com/romkatv/powerlevel10k) using the same coral/warm-gray
palette as the color themes and icon set.

Powerlevel10k's own ~/.p10k.zsh is a large generated config produced by its
`p10k configure` wizard -- not something this repo regenerates from scratch.
Instead this produces a small snippet to source *after* ~/.p10k.zsh, which
overrides just the segment colors below. See ROADMAP.md's "CLI / terminal
theme support" section.

Distributed as a downloadable asset (terminal/p10k-clay-terminal.zsh), not
bundled in the .vsix -- a VS Code extension can't install a shell config.

Run: python3 icons/generate_p10k.py
"""
import os

from palette import CORAL, WARM_GRAY

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(ROOT, "..", "terminal", "p10k-clay-terminal.zsh")

SCRIPT = f'''# Clay Terminal Powerlevel10k color override -- coral accent ({CORAL}),
# warm-gray neutrals ({WARM_GRAY}), generated by icons/generate_p10k.py from
# icons/palette.py.
#
# Powerlevel10k's own ~/.p10k.zsh is a large generated config (from the
# `p10k configure` wizard), not something this snippet replaces. Source it
# *after* ~/.p10k.zsh in your ~/.zshrc so it overrides just the segment
# colors below:
#
#   source ~/.p10k.zsh
#   source ~/.p10k-clay-terminal.zsh
#
# Requires a terminal with 24-bit color support -- p10k's *_FOREGROUND /
# *_BACKGROUND variables accept hex colors directly.

typeset -g POWERLEVEL9K_DIR_FOREGROUND='{WARM_GRAY}'

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='{CORAL}'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='{CORAL}'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='{CORAL}'

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{{VIINS,VICMD}}_FOREGROUND='{CORAL}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{{VIINS,VICMD}}_FOREGROUND='{CORAL}'
'''

if __name__ == "__main__":
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(SCRIPT)
    print(f"Wrote {OUT_PATH}")
