"""Generates a Kitty color scheme (kitty.conf) from the 16-color ANSI palette
already defined in the dark color theme (themes/claude-code-color-theme.json),
so this scheme can never drift from what the theme actually ships.

Distributed as a downloadable asset (terminal/kitty.conf), not bundled in the
.vsix -- a VS Code extension can't install a terminal emulator's config.
Fourth and final format shipped under ROADMAP.md's "Terminal emulator color
schemes" item (CLI / terminal theme support section), after Windows Terminal
in v0.7.6, iTerm2 in v0.7.7, and Alacritty in v0.7.8.

Run: python3 icons/generate_kitty.py
"""
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
THEME_PATH = os.path.join(ROOT, "..", "themes", "claude-code-color-theme.json")
OUT_PATH = os.path.join(ROOT, "..", "terminal", "kitty.conf")

# Kitty color-slot index -> theme's terminal.ansi* suffix, in the standard
# black/red/green/yellow/blue/magenta/cyan/white order.
ANSI_NAMES = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]

with open(THEME_PATH) as f:
    colors = json.load(f)["colors"]

lines = [
    "# Clay Terminal color scheme for Kitty.",
    "# Generated by icons/generate_kitty.py from the dark color theme's own",
    "# terminal.ansi* colors -- do not edit by hand.",
    "",
    f"foreground {colors['terminal.foreground']}",
    f"background {colors['terminal.background']}",
    f"cursor {colors['terminalCursor.foreground']}",
    f"selection_foreground {colors['terminal.foreground']}",
    f"selection_background {colors['list.activeSelectionBackground']}",
    "",
]
for i, name in enumerate(ANSI_NAMES):
    ansi_suffix = name.capitalize()
    lines.append(f"color{i} {colors[f'terminal.ansi{ansi_suffix}']}")
    lines.append(f"color{i + 8} {colors[f'terminal.ansiBright{ansi_suffix}']}")

if __name__ == "__main__":
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}")
