"""Generates an Alacritty color scheme (TOML) from the 16-color ANSI palette
already defined in the dark color theme (themes/claude-code-color-theme.json),
so this scheme can never drift from what the theme actually ships.

Distributed as a downloadable asset (terminal/alacritty.toml), not bundled in
the .vsix -- a VS Code extension can't install a terminal emulator's config.
Third format shipped under ROADMAP.md's "Terminal emulator color schemes"
item (CLI / terminal theme support section), after Windows Terminal in
v0.7.6 and iTerm2 in v0.7.7; Kitty remains for a later cycle.

Run: python3 icons/generate_alacritty.py
"""
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
THEME_PATH = os.path.join(ROOT, "..", "themes", "claude-code-color-theme.json")
OUT_PATH = os.path.join(ROOT, "..", "terminal", "alacritty.toml")

# Alacritty color-scheme key -> theme's terminal.ansi* suffix.
ANSI_MAP = {
    "black": "Black", "red": "Red", "green": "Green", "yellow": "Yellow",
    "blue": "Blue", "magenta": "Magenta", "cyan": "Cyan", "white": "White",
}

with open(THEME_PATH) as f:
    colors = json.load(f)["colors"]

lines = [
    "# Clay Terminal color scheme for Alacritty.",
    "# Generated by icons/generate_alacritty.py from the dark color theme's",
    "# own terminal.ansi* colors -- do not edit by hand.",
    "",
    "[colors.primary]",
    f"background = \"{colors['terminal.background']}\"",
    f"foreground = \"{colors['terminal.foreground']}\"",
    "",
    "[colors.cursor]",
    f"text = \"{colors['terminal.background']}\"",
    f"cursor = \"{colors['terminalCursor.foreground']}\"",
    "",
    "[colors.selection]",
    f"text = \"{colors['terminal.foreground']}\"",
    f"background = \"{colors['list.activeSelectionBackground']}\"",
    "",
    "[colors.normal]",
]
for alacritty_key, ansi_name in ANSI_MAP.items():
    lines.append(f"{alacritty_key} = \"{colors[f'terminal.ansi{ansi_name}']}\"")

lines += ["", "[colors.bright]"]
for alacritty_key, ansi_name in ANSI_MAP.items():
    lines.append(f"{alacritty_key} = \"{colors[f'terminal.ansiBright{ansi_name}']}\"")

if __name__ == "__main__":
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}")
