"""Generates a Starship (https://starship.rs) prompt preset using the same
coral/warm-gray palette as the color themes and icon set.

Distributed as a downloadable asset (terminal/starship.toml), not bundled in
the .vsix -- a VS Code extension can't install a shell prompt config. See
ROADMAP.md's "CLI / terminal theme support" section.

Run: python3 icons/generate_starship.py
"""
import os

from palette import CORAL, WARM_GRAY

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(ROOT, "..", "terminal", "starship.toml")

TOML = f'''"$schema" = "https://starship.rs/config-schema.json"

# Clay Terminal Starship preset -- coral accent ({CORAL}), warm-gray neutrals
# ({WARM_GRAY}), generated by icons/generate_starship.py from icons/palette.py.
# Install: copy to ~/.config/starship.toml (or merge with your existing config).

format = """
$directory\\
$git_branch\\
$git_status\\
$character"""

[character]
success_symbol = "[❯](bold {CORAL})"
error_symbol = "[❯](bold {CORAL})"
vimcmd_symbol = "[❮](bold {CORAL})"

[directory]
style = "bold {WARM_GRAY}"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "{CORAL}"
symbol = " "

[git_status]
style = "bold {CORAL}"

[cmd_duration]
style = "{WARM_GRAY}"
format = "took [$duration]($style) "
'''

if __name__ == "__main__":
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(TOML)
    print(f"Wrote {OUT_PATH}")
