# Clay Terminal Powerlevel10k color override -- coral accent (#D97757),
# warm-gray neutrals (#C3C2B7), generated by icons/generate_p10k.py from
# icons/palette.py.
#
# Powerlevel10k's own ~/.p10k.zsh is a large generated config (from the
# `p10k configure` wizard), not something this snippet replaces. Source it
# *after* ~/.p10k.zsh in your ~/.zshrc so it overrides just the segment
# colors below:
#
#   source ~/.p10k.zsh
#   source ~/.p10k-clay-terminal.zsh
#
# Requires a terminal with 24-bit color support -- p10k's *_FOREGROUND /
# *_BACKGROUND variables accept hex colors directly.

typeset -g POWERLEVEL9K_DIR_FOREGROUND='#C3C2B7'

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#D97757'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#D97757'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#D97757'

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD}_FOREGROUND='#D97757'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD}_FOREGROUND='#D97757'
